language: ruby
sudo: required
dist: trusty
rvm:
  - 2.2
  - 2.3
  - jruby-9.0.5.0
  - rbx-3.26
gemfile:
  - Gemfile
matrix:
  include:
    - gemfile: Gemfile
      env: WINDOW_TEST=true
    - gemfile: gemfiles/Gemfile.rspec-34
      rvm: 2.3.1
      env: CAPYBARA_CHROME=true
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
            - awesome
    - gemfile: gemfiles/Gemfile.beta-versions
      rvm: 2.4.0-preview1
    - gemfile: gemfiles/Gemfile.beta-marionette
      env: GECKODRIVER=true
      rvm: 2.3.1
      addons:
        firefox: latest-beta
        apt:
          packages:
            - awesome
  allow_failures:
    - gemfile: gemfiles/Gemfile.beta-versions
    - gemfile: gemfiles/Gemfile.beta-marionette
    - rvm: jruby-9.0.5.0
    - rvm: rbx-3.26
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  firefox: 47.0.1
  apt:
    packages:
      - awesome

before_install:
  - if [ $CAPYBARA_CHROME ]; then
      CHROMEDRIVER_VERSION=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE);
      CHROMEDRIVER_URL="http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip";
      FILE=`mktemp`; wget "$CHROMEDRIVER_URL" -qO $FILE && unzip $FILE chromedriver -d ~; rm $FILE; chmod 777 ~/chromedriver;
    fi
  - if [ $GECKODRIVER ]; then
      GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz";
      FILE=`mktemp`; wget "$GECKODRIVER_URL" -qO $FILE && tar xz -C ~ -f $FILE geckodriver; rm $FILE; chmod 777 ~/geckodriver;
    fi
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1
  - mkdir -p ~/.config/awesome
  - echo "require('awful'); tags = {}; tags[1] = awful.tag({'name'})" > ~/.config/awesome/rc.lua
  - "awesome &"
script: "bundle exec rake travis"
